### ISSUE TITLE
./dist shouldn't be committed

### ISSUE THREAD

**Issue by jameslnewell** [nib-components/react-scale-slider#1]
because we won't be using this repo with our legacy `componentjs` apps

**Comment by laurie-jones** [comment]
Just remove it from the project entirely?

**Comment by jameslnewell** [comment]
Add it to the `.gitignore` and then `git rm --cached ./dist`

**Comment by jameslnewell** [comment]
ping @lauriejones 

Is this done?

**Comment by lauriejones** [comment]
Yep, done!
